apiVersion: v1
kind: ServiceAccount
metadata:
  name: containerscale-controller
  namespace: kube-system
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-autoscaler:containerscale-manager
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes"]
  verbs: ["update", "get", "watch", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["*"]
- apiGroups: ["systemautoscaler.polimi.it"]
  resources: ["servicelevelagreements"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["systemautoscaler.polimi.it"]
  resources: ["containerscales"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-autoscaler:containerscale-manager
subjects:
- kind: ServiceAccount
  name: containerscale-controller
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: system-autoscaler:containerscale-manager
  apiGroup: rbac.authorization.k8s.io
