apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: prime-numbers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prime-numbers
  minReplicas: 1
  maxReplicas: 30
  metrics:
    - type: Object
      object:
        metric:
          name: response_time
        describedObject:
          apiVersion: /v1
          kind: Service
          name: prime-numbers
        target:
          type: Value
          value: 200m
