apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
  name: prime-numbers-1
spec:
  metric:
    responseTime: 200m
  defaultResources:
    memory: 128Mi
    cpu: 250m
  minResources:
    memory: 64Mi
    cpu: 500m
  maxResources:
    memory: 256Mi
    cpu: 8000m
  service:
    container: prime-numbers-1
    selector:
      matchLabels:
        app: prime-numbers-1
