apiVersion: v1
kind: ServiceAccount
metadata:
  name: podscale-controller
  namespace: kube-system
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-autoscaler:podscale-controller
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "nodes"]
    verbs: ["update", "get", "watch", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["*"]
  - apiGroups: ["systemautoscaler.polimi.it"]
    resources: ["servicelevelagreements"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["systemautoscaler.polimi.it"]
    resources: ["podscales"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-autoscaler:podscale-controller
subjects:
  - kind: ServiceAccount
    name: podscale-controller
    namespace: kube-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: system-autoscaler:podscale-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podscale-controller
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: podscale-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: podscale-controller
    spec:
      automountServiceAccountToken: true
      serviceAccountName: podscale-controller
      containers:
        - name: podscale-controller
          image: systemautoscaler/podscale-controller:0.1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi


