apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-autoscaler
  namespace: kube-system
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-autoscaler:pod-autoscaler
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "nodes"]
    verbs: ["update", "get", "watch", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["*"]
  - apiGroups: ["systemautoscaler.polimi.it"]
    resources: ["servicelevelagreements"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["systemautoscaler.polimi.it"]
    resources: ["podscales"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-autoscaler:pod-autoscaler
subjects:
  - kind: ServiceAccount
    name: pod-autoscaler
    namespace: kube-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: system-autoscaler:pod-autoscaler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-autoscaler
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pod-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-autoscaler
    spec:
      automountServiceAccountToken: true
      serviceAccountName: pod-autoscaler
      containers:
        - name: pod-autoscaler
          image: pentabanana/pod-autoscaler:latest
          imagePullPolicy: Always
