apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: example-nginx
    spec:
      containers:
      - name: example-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-nginx
  labels:
    app: example-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: example-nginx
