apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerscale-controller
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: containerscale-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: containerscale-controller
    spec:
      automountServiceAccountToken: true
      serviceAccountName: containerscale-controller
      containers:
      - name: containerscale-controller
        image: lterrac/containerscale-controller:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi

