apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-monitoring
  namespace: default
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-autoscaler:sa-monitoring
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "nodes"]
    verbs: ["update", "get", "watch", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["*"]
  - apiGroups: ["systemautoscaler.polimi.it"]
    resources: ["servicelevelagreements"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["systemautoscaler.polimi.it"]
    resources: ["podscales"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-autoscaler:sa-monitoring
subjects:
  - kind: ServiceAccount
    name: sa-monitoring
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: system-autoscaler:sa-monitoring
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-1
spec:
  selector:
    matchLabels:
      app: monitoring-1
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring-1
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      automountServiceAccountToken: true
      serviceAccountName: sa-monitoring
      containers:
        - name: monitoring-1
          image: systemautoscaler/system-autoscaler-monitoring
          imagePullPolicy: Always
