name: E2E

on:
  - pull_request

jobs:

  e2e:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        run: |
          kubectl get pods --all-namespaces
