apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ContainerScale
metadata:
  name: example-containerscale
spec:
  serviceLevelAgreement:
    name: example-sla
    namespace: foo
  pod:
    name: example-sa
    namespace: foo
  desired:
    cpu: 40m
    memory: 70Mi
status: {}
